### autogenerated from R -e 'knitr::purl(16-infercnv.Rmd)'
### autogenerated from R -e 'knitr::purl(16-infercnv.Rmd)'
### autogenerated from R -e 'knitr::purl(16-infercnv.Rmd)'
## ----setup, include=FALSE-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
suppressMessages(library(rmarkdown))
knitr::opts_chunk$set(echo = TRUE,
  fig.width=9,
  fig.height=6,
  cache=TRUE, # only use TRUE if you're really sure. Also check xfun::cache_rds
  cache.comments=FALSE,
  collapse=TRUE,  # put misc. outputs from one chunk in one block
  tidy=TRUE, # tidies up the R code
  tidy.opts=list(arrow=TRUE, 
                 indent=2,
                 width.cutoff = 60))


## ----loadsession, include=FALSE-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
source('../libs.R')
load("../15-singler/session.rda")
data(refdata_cellranger_GRCh38_3.0.0)


## ----prepare-infercnv-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## overview of numbers per celltype:
table(srat@meta.data$type2)

## which cells do we think we can trust as being healthy:
ref_types <- c("T", "NK", "B", "Mono")

## overview of this:
maybe_tumor <- !(srat@meta.data$type2 %in% ref_types)
table( maybe_tumor )

## infercnv needs them as an external data file in a specific format,
## create that:
df <- data.frame(cell=colnames(srat), type=srat@meta.data$type2)

celltypes_file <- paste0(CFG$output_dir,"/celltypes.txt")
write.table(df, file=celltypes_file, sep="\t", 
  quote=FALSE, na="", row.names=FALSE, col.names=FALSE)

## infercnv also needs to gene coordinates, in the tab-delimited format
##  genename chrNN START END. 
## We can use the `genecoords` object from SCutils for this.

## this data needs some cleaning. Use only the canonical chromosomes,
## sort them, get rid of duplicates and put 'chr' in front of the chromosome:
wanted.chr <- c( as.character(1:22), "X", "Y") # skip MT and KI2707 etc.
geneorder <- genecoords[ genecoords$chr %in% wanted.chr,  ]
geneorder$numeric_chr <- as.numeric(geneorder$chr)
geneorder[ geneorder$chr %in% 'X', 'numeric_chr' ] <- 30
geneorder[ geneorder$chr %in% 'Y', 'numeric_chr' ] <- 40
geneorder <- geneorder[ order(geneorder$numeric_chr, geneorder$start), ]
geneorder <- geneorder[!duplicated(geneorder$gene_name), ]
geneorder <- with(geneorder,
                  data.frame(gene=gene_name,
                             chromosome=paste0('chr', chr),
                             start=start, end=end))

geneorder_file <- paste0(CFG$output_dir, "/geneorder.txt")
write.table(geneorder, file=geneorder_file, sep="\t",
            row.names=FALSE, col.names=FALSE,
            quote=FALSE, na="")

raw_counts <- GetAssayData(srat, assay='RNA', slot='counts')

common <- intersect(rownames(raw_counts), geneorder$gene)

## set up the infercnv object with all necessary information:
infercnv_obj <- infercnv::CreateInfercnvObject(delim="\t",
      raw_counts_matrix=raw_counts[common, ] ,
      annotations_file=celltypes_file,
      gene_order_file=geneorder_file,
      ref_group_name = ref_types )

## free up space before we start:
gc()



## ----infercnv-run---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## infercnv writes its output to disk. It is a fair amount,
## so let's create a separate directory for that and write
## it there:
outdir <- paste0(CFG$output_dir, "/infercnv")
dir.create(outdir)

## running takes can take up to 10 min, best start this before the lecture:
infercnv_obj <- infercnv::run(infercnv_obj,
                             out_dir=outdir,
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             analysis_mode = "samples",
                             num_threads = 3,
                             output_format = "png",
                             window_length = 101,
                             save_final_rds = TRUE,
                             plot_steps=FALSE, 
                             cutoff=0.1, 
                             sd_amplifier = 1.5,
                             HMM=FALSE)

## plot_steps=TRUE may lead to weird crash, see github
## cutoff: min average read counts per gene for reference cells
## sd_amplifier: noise threshold. Higher: less noise but also less signal.



## ----copyoutput, include=FALSE--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

png <- list.files(outdir, pattern = "^infercnv.png$", full.names = TRUE)
file.copy(png, "figure/", overwrite=TRUE)



## ----prep-aneuploidy------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

refexp <- infercnv_obj@expr.data[ , unname(unlist(infercnv_obj@reference_grouped_cell_indices)) ]

obsexp <- infercnv_obj@expr.data[ , unname(unlist(infercnv_obj@observation_grouped_cell_indices)) ]

## now scale them so that SD is the 'unit' of Modif. Expression:
obs.scaled <- scale(obsexp)
ref.scaled <- scale(refexp)

## trick by Jurrian de Kanter
.count_genes_in_runs <- function (x, length=50, SDs=2) {
  ## count total number of genes in stretches longer than LENGTH 
  ## exceeding SDs std.devs from mean. 
  runs <- rle(x > SDs)
  up <- sum(runs$lengths[ runs$lengths>length & runs$values])
  runs <- rle(x <   -SDs)
  down <- sum(runs$lengths[ runs$lengths>length & runs$values])
  ## (don't use abs(x) >  because pos and neg stretches might overlap, so partly cancel)
  sum(up,down)
} # .count_genes_in_runs

aneuploidy_score <- function(adj_expr,
                     length = 70,
                     SDs = 1.5) {
  apply(adj_expr, 2, .count_genes_in_runs, length=length, SDs=SDs)
}  ## aneuploidy_score



## ----calc-score-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

len <- 50 # also try e.g. 30 or 70
SDs <- 1.3 # also try e.g. 1.5 or 2
obsscore <-  aneuploidy_score(obs.scaled, length=len)
refscore <-  aneuploidy_score(ref.scaled, SDs=SDs)

ttest <- t.test(obsscore, refscore)

plot(density(obsscore), 
      main=sprintf("Aneuploidy score length=%d SDs=%.1f",len, SDs),
      xlab=sprintf("t=%.2f", ttest$statistic))
rug(obsscore, ticksize=0.01)
rug(refscore, ticksize= -0.01, col='red')
lines(density(refscore), col='red')
legend(x="topright", legend=c('tumor', 'reference'), col=c('black','red'),
       pch=NULL, lty=1, bty='n')



## ----plot-aneuploidy------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

allscore <- c(obsscore,refscore)
allscore <- allscore[ colnames(srat) ] # put in order of srat object.
srat <- AddMetaData(srat, col.name='aneuploidy_score', allscore)

cutoff <- 600 # based on the density plot

aneuploid <- ifelse( srat@meta.data$aneuploidy_score < cutoff, 'no', 'yes')
srat <- AddMetaData(srat, col.name='is_aneuploid', aneuploid)

## Let's show all we have. If it's too much information, leave some of it out.

p_plate <- DimPlot(srat, reduction = "umap", pt.size=0.5,
  group.by='plate_id')

p_patient <- DimPlot(srat, reduction = "umap", pt.size=0.5,
  group.by='patient')

p_celltype <- DimPlot(srat, reduction = "umap", pt.size=0.5,
  group.by='type2')

p_status <- DimPlot(srat, reduction = "umap", pt.size=0.5,
  group.by='type')

p_aneup <- FeaturePlot(srat, reduction = "umap", pt.size=0.5,
    features='aneuploidy_score',
    cols=CFG$gradient.colors, order=TRUE)

p_isaneup <- DimPlot(srat, reduction = "umap", pt.size=0.5,
  group.by='is_aneuploid')

 ( p_plate | p_patient | p_celltype ) / 
( p_status | p_aneup | p_isaneup )



## ----savesession, include=FALSE-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## save complete state for next lesson
## save.image("session.rda")
if(Sys.getenv("nodump")!="TRUE")
    save(file="session.rda", list=c("srat", ls(pat="col|CFG")))

