## main Jekyll config. If you render Jekyll locally, be sure to clear the cache
## first, e.g. as
##   rm -fr _site
##   bundle exec jekyll serve --incremental  --port 4321
## (in contrast, changes in the *.md _are_ noticed and re-rendered automatically)
title: Single-cell RNA-seq data analysis with R
description: Single-cell RNA-seq data analysis with R
exclude:
  - "*/*.R"
  - "*/*.Rmd"
  - "*/*.log"
  - "*/session.rda"
  - "*/session.rdaTmp"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

### theme related stuff:
theme: jekyll-theme-leap-day
## remote_theme: pmarsceill/just-the-docs ## see also local_config.yml
## theme: "just-the-docs"

nav_order: 0 

search_enabled: false
## color_scheme: dark
color_scheme: light
heading_anchors: true  
footer_content: "Brought to you by the Princess Maxima Center Single-Cell Facility"
# Footer last edited timestamp
## last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
## last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
back_to_top: true
back_to_top_text: "Back to top"

## TOC: see pages themselves
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - course.md


## Note: 'title:' is/should be overriden in each page.
## 'description:' is shown as subtitle, is not overriden.

## custom variables. Use them as eg. {{ site.course_date }} in your markdown
## When using jekyll locally be sure to clear the cache and restart the server
course_date: "Mon 24 Jan - Tue 25 Jan 2022"
registration_url: "https://www.primaacademy.nl/pmc/servlet/ekp?CID=EKP000001863&TX=FORMAT1&BACKTOCATALOG=Y&DECORATEPAGE=N"

